name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
      - run: CC=${{ matrix.compiler }} make
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y clang-tools
      - run: scan-build -analyze-headers --status-bugs make
