name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            target: all
          - compiler: clang
            target: all
          - compiler: x86_64-w64-mingw32-gcc
            deb: gcc-mingw-w64-x86-64
            target: win32
          - compiler: i686-w64-mingw32-gcc
            deb: gcc-mingw-w64-i686
            target: win32
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ${{ matrix.deb }}
        if: ${{ matrix.deb != '' }}
        run: sudo apt-get install -y ${{ matrix.deb }}
      - name: Build using ${{ matrix.compiler }}
        run: CC=${{ matrix.compiler }} make -k ${{ matrix.target }}
  macosx:
    name: Build (macosx)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check the code
        run: make -k all
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install scan-build
        run: sudo apt-get install -y clang-tools
      - name: Check the code
        run: scan-build -analyze-headers --status-bugs make all
